# Generated by Django 5.2.5 on 2025-09-04 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='assigned_nutritionist',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'nutricionista'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL),
        ),
    ]
